### ISSUE TITLE
Fix uncss in gulp file

### ISSUE THREAD

**Issue by jaevans36** [jaevans36/starter-kit#1]
This error needs to be fixed, and is happening when running gulp deploy - likely cause is in the uncss task in gulp.

```
C:\Sites\starter-kit\node_modules\uncss\node_modules\bluebird\js\release\async.js:48
        fn = function () { throw arg; };
                           ^
TypeError: Cannot read property 'map' of undefined
    at getHTML (C:\Sites\starter-kit\node_modules\uncss\src\uncss.js:29:28)
    at C:\Sites\starter-kit\node_modules\uncss\src\uncss.js:246:20
    at tryCatcher (C:\Sites\starter-kit\node_modules\uncss\node_modules\bluebird\js\release\util.js:11:23)
    at C:\Sites\starter-kit\node_modules\uncss\node_modules\bluebird\js\release\using.js:184:26
    at tryCatcher (C:\Sites\starter-kit\node_modules\uncss\node_modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (C:\Sites\starter-kit\node_modules\uncss\node_modules\bluebird\js\release\promise.js:491:31)
    at Promise._settlePromise (C:\Sites\starter-kit\node_modules\uncss\node_modules\bluebird\js\release\promise.js:548:18)
    at Promise._settlePromise0 (C:\Sites\starter-kit\node_modules\uncss\node_modules\bluebird\js\release\promise.js:593:10)
    at Promise._settlePromises (C:\Sites\starter-kit\node_modules\uncss\node_modules\bluebird\js\release\promise.js:676:18)
    at Promise._fulfill (C:\Sites\starter-kit\node_modules\uncss\node_modules\bluebird\js\release\promise.js:617:18)
    at PromiseArray._resolve (C:\Sites\starter-kit\node_modules\uncss\node_modules\bluebird\js\release\promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (C:\Sites\starter-kit\node_modules\uncss\node_modules\bluebird\js\release\promise_array.js:143:14)
    at Promise._settlePromise (C:\Sites\starter-kit\node_modules\uncss\node_modules\bluebird\js\release\promise.js:553:26)
    at Promise._settlePromise0 (C:\Sites\starter-kit\node_modules\uncss\node_modules\bluebird\js\release\promise.js:593:10)
    at Promise._settlePromises (C:\Sites\starter-kit\node_modules\uncss\node_modules\bluebird\js\release\promise.js:676:18)
    at Async._drainQueue (C:\Sites\starter-kit\node_modules\uncss\node_modules\bluebird\js\release\async.js:125:16)
```

**Comment by jaevans36** [comment]
Fixed in latest build - https://github.com/jaevans36/starter-kit/commit/0ffff22d2295e01de380caadeee52f72daac4c65
